# Generated by Django 4.0.2 on 2022-02-01 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.BigIntegerField(unique=True, verbose_name='hackernews-Id')),
                ('fetched_at', models.DateTimeField(default=datetime.datetime(2022, 2, 1, 17, 9, 45, 721356))),
            ],
        ),
    ]
