# Generated by Django 3.2 on 2022-02-04 13:43

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNewsID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackernews', models.BigIntegerField(unique=True)),
                ('fetched_at', models.DateTimeField(default=datetime.datetime(2022, 2, 4, 14, 43, 1, 679622))),
            ],
        ),
        migrations.CreateModel(
            name='QuickCheckItem',
            fields=[
                ('id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.hackernewsid')),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=100)),
                ('by', models.CharField(blank=True, max_length=255, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), default=list, size=None)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
