# Generated by Django 3.2 on 2022-02-01 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_id',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 19, 5, 44, 96038)),
        ),
    ]
