# Generated by Django 3.2 on 2022-02-02 13:05

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_id_fetched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.news_id')),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=100)),
                ('by', models.CharField(blank=True, max_length=255, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), size=None)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news_id',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 14, 5, 25, 224348)),
        ),
    ]
