# Generated by Django 3.2 on 2022-02-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220202_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='time',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news_id',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 14, 9, 13, 630046)),
        ),
    ]
