# Generated by Django 3.2 on 2022-02-02 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220202_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_id',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 14, 12, 59, 433330)),
        ),
    ]
