# Generated by Django 3.2 on 2022-02-02 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20220202_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_id',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 14, 18, 31, 536004)),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.news_id'),
        ),
    ]
