# Generated by Django 3.2 on 2022-02-04 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20220204_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsid',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 18, 0, 5, 78402)),
        ),
        migrations.AlterField(
            model_name='quickcheckitem',
            name='time',
            field=models.BigIntegerField(blank=True, default=1643994006, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quickchecknews',
            name='time',
            field=models.BigIntegerField(blank=True, default=1643994006, null=True, unique=True),
        ),
    ]
