# Generated by Django 3.2 on 2022-02-04 17:44

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220204_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsid',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 18, 44, 0, 647669)),
        ),
        migrations.AlterField(
            model_name='quickcheckitem',
            name='kids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True, unique=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='quickcheckitem',
            name='time',
            field=models.BigIntegerField(blank=True, default=1643996641, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quickchecknews',
            name='kids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True, unique=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='quickchecknews',
            name='time',
            field=models.BigIntegerField(blank=True, default=1643996641, null=True, unique=True),
        ),
    ]
