# Generated by Django 3.2 on 2022-02-06 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20220204_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsid',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 22, 50, 54, 124822)),
        ),
        migrations.AlterField(
            model_name='quickcheckitem',
            name='time',
            field=models.BigIntegerField(blank=True, default=1644184255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quickchecknews',
            name='by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickchecknews',
            name='time',
            field=models.BigIntegerField(blank=True, default=1644184255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quickchecknews',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
