# Generated by Django 3.2 on 2022-03-10 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20220207_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernewsid',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 9, 41, 7, 178565)),
        ),
        migrations.AlterField(
            model_name='quickcheckitem',
            name='time',
            field=models.BigIntegerField(blank=True, default=1646901668, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quickchecknews',
            name='time',
            field=models.BigIntegerField(blank=True, default=1646901668, null=True, unique=True),
        ),
    ]
